# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "types",
    "config",
    "crypto",
    "consensus",
    "main",
]

# This is just a collection of packages that builds Optrand